version: "3"

services:
  postgres:
    container_name: postgres1
    image: postgres:12.3-alpine
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - backend-db
    volumes:
      - postgres:/var/home/noam/Documents/web/todo.app/postgresql/data

  frontend:
    env_file: .env
    restart: always
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npx nx serve apps-frontend --host=0.0.0.0
    ports:
      - 4200:4200
    networks:
      - backend-frontend

  backend:
    env_file: .env
    restart: always
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run backend:migrate --host=0.0.0.0
    ports:
      - 3333:3333
      - 8080:8080
      - 3030:3030
    networks:
      - backend-db
      - backend-frontend

networks:
  backend-db:
  backend-frontend:

volumes:
  postgres:
