version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:12.3-alpine
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/home/noam/Documents/web/todo.app/postgresql/data

volumes:
  postgres:
