version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:12.3-alpine
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/home/noam/Documents/web/todo.app/postgresql/data
  frontend:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npx nx serve apps-frontend --host 0.0.0.0
    ports:
      - 4200:4200

volumes:
  postgres:
