version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:12.3-alpine
    restart: always
    env_file: ./.env
    networks:
      - backend-postgres
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data

  frontend:
    hostname: ${HOSTNAME}
    restart: always
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command:  npx nx serve apps-frontend --host=0.0.0.0 --port=${FRONTEND_PORT}
    environment:
      - HOSTNAME=${HOSTNAME},
      - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    networks:
      - backend-frontend
    volumes:
      - ./assets/img/user/:/app/assets/img/user/

  backend:
    hostname: ${HOSTNAME}
    restart: always
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run backend:migrate:start --host=0.0.0.0 --port=${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
      - ${SOCKET_CHAT}:${SOCKET_CHAT}
      - ${SOCKET_GAME}:${SOCKET_GAME}
    networks:
      - backend-postgres
      - backend-frontend

networks:
  backend-postgres:
  backend-frontend:

volumes:
  postgres:
  backend:
