version: "3"

networks:
  isolation-network:
    driver: bridge

services:
    postgres:
        image: postgres:12.3-alpine
        env_file:
          ./environnement/dev.env
        volumes:
          - postgres:/var/home/noam/Documents/web/todo.app/postgresql/data
        ports:
          - ${POSTGRES_ENV_PORT}:${POSTGRES_ENV_PORT}
        restart: always
        networks:
          - isolation-network
  
    pgadmin:
        image: dpage/pgadmin4:6.11
        env_file:
          ./environnement/dev.env
        ports:
            - 15432:80
        volumes:
            - pgadmin:/var/home/noam/Documents/web/todo.app/pgadmin
        depends_on:
            - postgres

    backend:
        container_name: backend
        build:
          dockerfile: ./Dockerfile
          context: ./srcs/backend
        expose:
          - "${BACK_ENV_PORT}"
        env_file:
          ./environnement/dev.env
        ports:
          - "${BACK_ENV_PORT}:${BACK_ENV_PORT}"
        networks:
          - isolation-network
    
    frontend:
        container_name: frontend
        build:
          dockerfile: ./Dockerfile
          context: ./srcs/frontend
        env_file:
          ./environnement/dev.env
        expose:
          - "${PORT}"
        ports:
          - "${PORT}:${PORT}"
        networks:
          - isolation-network

volumes:
    postgres:
    pgadmin:
